### ISSUE TITLE
Setup Kanban Board

### ISSUE THREAD

**Issue by NicolasAndrehh** [NicolasAndrehh/Things-Catalog#21]
## Hey Code Reviewer! 😄
You can check the Kanban board by clicking on [this link](https://github.com/NicolasAndrehh/Things-Catalog/projects/1)

## Team members 
There are 3 people on our team
- @dicodiaz (Team member 1)
- @NicolasAndrehh (Team member 2)
- @rashedarman (Team member 3)
<img src="https://media0.giphy.com/media/118Ue8iVVEYR5S/giphy.gif"/>

**Comment by Ismailco** [comment]
### Hi @NicolasAndrehh, @dicodiaz, @rashedarman,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️  Create Kanban board
✔️ All cards have a description
✔️ The tasks are divided fairly

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
